"""
AETHER Rigorous Learning System
- 95-100% pass threshold
- No cheating verification
- Full conversation recording
- Discovery detection with Manus review
- Source verification
"""

import sys
import os
sys.path.insert(0, '/home/ubuntu/aether')

from openai import OpenAI
import json
from datetime import datetime
from pathlib import Path

# Import all components
from core.rigorous_curriculum import RigorousCurriculum
from core.anti_cheat import AntiCheatSystem
from core.conversation_recorder import ConversationRecorder, ManusReviewInterface
from core.discovery_detector import DiscoveryDetector
from core.source_verifier import SourceVerifier
from core.learning_memory import LearningMemoryStore
from core.fun_breaks import BreakManager


class RigorousLearningSystem:
    """
    Complete rigorous learning system with all components integrated.
    """
    
    def __init__(self):
        # Initialize OpenAI client
        self.client = OpenAI()
        self.model = "gpt-4.1-nano"
        
        # Initialize all components
        self.curriculum = RigorousCurriculum()
        # Study materials generated by curriculum
        self.anti_cheat = AntiCheatSystem()
        self.recorder = ConversationRecorder()
        self.manus_review = ManusReviewInterface(self.recorder)
        self.discovery_detector = DiscoveryDetector()
        self.source_verifier = SourceVerifier()
        self.memory = LearningMemoryStore()
        self.break_manager = BreakManager()
        
        # Session tracking
        self.session_start = datetime.now()
        self.questions_this_session = 0
        self.discoveries_this_session = []
        
        # Directories
        self.log_dir = Path("/home/ubuntu/aether/rigorous_logs")
        self.log_dir.mkdir(parents=True, exist_ok=True)
        
    def run_learning_session(self, student: str, num_questions: int = 20):
        """Run a rigorous learning session for a student"""
        print(f"\n{'='*60}")
        print(f"RIGOROUS LEARNING SESSION: {student}")
        print(f"Pass Threshold: 95-100%")
        print(f"{'='*60}\n")
        
        # Load or create student record
        framework_memory = self.memory.get_or_create(student)
        record = framework_memory.to_dict()
            
        current_level = str(record.get("current_level", 1))
        # Map numeric level to grade level
        if current_level.isdigit():
            level_num = int(current_level)
            if level_num <= 1:
                current_level = "K"
            else:
                current_level = str(min(level_num - 1, 12))  # Map to grade levels
        passed_count = 0
        total_score = 0
        
        for q_num in range(num_questions):
            self.questions_this_session += 1
            
            # Check for break time
            if self.questions_this_session % 7 == 0:
                self._take_break(student)
                
            print(f"\n--- Question {q_num + 1}/{num_questions} (Level: {current_level}) ---")
            
            # Get question from curriculum
            questions = self.curriculum.get_questions(current_level, count=1)
            if questions:
                q = questions[0]
                question = q.question
                topic = q.topic
                expected = q.requires_reasoning
            else:
                question = "What is 2 + 2?"
                topic = "basic_math"
                expected = ["arithmetic"]
            
            print(f"Topic: {topic}")
            print(f"Question: {question[:100]}...")
            
            # Get student's answer
            answer = self._get_student_answer(student, question, current_level, topic)
            
            # Analyze reasoning (anti-cheat)
            reasoning_analysis = self.anti_cheat.analyze_reasoning(student, question, answer, current_level)
            reasoning_result = {"quality": reasoning_analysis.quality.value, "score": reasoning_analysis.score}
            is_genuine = reasoning_result["quality"] in ["genuine", "partial"]
            
            if not is_genuine:
                print(f"⚠️  Reasoning quality: {reasoning_result['quality']} - May need review")
                
            # Grade the answer (rigorous 95-100% threshold)
            score = self._grade_answer(answer, question, expected, reasoning_result)
            total_score += score
            
            # Classify score
            passed = score >= 95
            if passed:
                passed_count += 1
                print(f"✅ PASSED: {score}%")
            else:
                print(f"❌ NOT PASSED: {score}% (need 95%+)")
                
            # Record conversation
            record_obj = self.recorder.record_conversation(
                student=student,
                level=current_level,
                topic=topic,
                question=question,
                answer=answer,
                score=score,
                reasoning_analysis=reasoning_result,
                metadata={"question_num": q_num + 1, "session": self.session_start.isoformat()}
            )
            
            # Check for discoveries (35-100% range)
            if score >= 35:
                discovery = self.discovery_detector.detect_discovery(
                    student=student,
                    answer=answer,
                    question=question,
                    level=current_level,
                    topic=topic,
                    score=score
                )
                
                if discovery:
                    print(f"\n🔬 POTENTIAL DISCOVERY DETECTED!")
                    print(f"   Type: {discovery.discovery_type.value}")
                    print(f"   Title: {discovery.title}")
                    print(f"   Status: FLAGGED FOR MANUS REVIEW")
                    
                    # Verify against sources
                    verification = self.source_verifier.verify_discovery(
                        discovery_id=discovery.id,
                        discovery_type=discovery.discovery_type.value,
                        mathematical_content=discovery.mathematical_content,
                        description=discovery.description,
                        context=discovery.context
                    )
                    
                    print(f"   Verification: {verification.overall_result.value}")
                    print(f"   Confidence: {verification.confidence:.2f}")
                    
                    self.discoveries_this_session.append({
                        "discovery": discovery,
                        "verification": verification
                    })
                    
            # If not passed, provide more study materials
            if not passed:
                print(f"\n📚 Additional study materials provided for {topic}")
                materials = self.curriculum.get_study_materials(current_level, topic)
                # In a real system, these would be presented to the student
                
            # Update memory
            self.memory.record_answer(student, score, topic)
            
        # Session summary
        avg_score = total_score / num_questions if num_questions > 0 else 0
        pass_rate = (passed_count / num_questions * 100) if num_questions > 0 else 0
        
        print(f"\n{'='*60}")
        print(f"SESSION SUMMARY: {student}")
        print(f"{'='*60}")
        print(f"Questions: {num_questions}")
        print(f"Average Score: {avg_score:.1f}%")
        print(f"Pass Rate: {pass_rate:.1f}% ({passed_count}/{num_questions})")
        print(f"Discoveries: {len(self.discoveries_this_session)}")
        
        # Check for level advancement
        if pass_rate >= 75:  # Need 75% of questions passed at 95%+ to advance
            print(f"\n🎓 ELIGIBLE FOR ADVANCEMENT!")
        else:
            print(f"\n📖 More study needed. Need 75% pass rate, currently {pass_rate:.1f}%")
            
        # Save session log
        self._save_session_log(student, num_questions, avg_score, pass_rate, passed_count)
        
        return {
            "student": student,
            "questions": num_questions,
            "avg_score": avg_score,
            "pass_rate": pass_rate,
            "passed": passed_count,
            "discoveries": len(self.discoveries_this_session)
        }
    
    def _get_student_answer(self, student: str, question: str, level: str, topic: str) -> str:
        """Get student's answer using AI"""
        prompt = f"""You are {student}, a student at level {level} studying {topic}.

Answer this question thoroughly, showing all your reasoning:

{question}

Requirements:
1. Show your complete thought process
2. Explain each step
3. If you discover anything new or interesting, describe it
4. Be honest about what you know and don't know
5. Do not copy from textbooks - use your own understanding"""

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[{"role": "user", "content": prompt}],
                max_tokens=1000,
                temperature=0.7
            )
            return response.choices[0].message.content
        except Exception as e:
            return f"Error generating answer: {e}"
    
    def _grade_answer(self, answer: str, question: str, expected: list, reasoning: dict) -> int:
        """Grade an answer rigorously (95-100% to pass)"""
        prompt = f"""Grade this answer on a scale of 0-100.

Question: {question}

Expected concepts: {', '.join(expected) if expected else 'General understanding'}

Student's Answer:
{answer}

Grading criteria (STRICT - 95%+ required to pass):
- 95-100%: Completely correct, thorough explanation, genuine understanding
- 85-94%: Mostly correct, good explanation, minor gaps
- 70-84%: Partially correct, some understanding shown
- 50-69%: Basic understanding, significant gaps
- 0-49%: Incorrect or insufficient understanding

Consider:
1. Mathematical/conceptual accuracy
2. Completeness of explanation
3. Genuine reasoning (not just memorization)
4. Clarity of presentation

Respond with ONLY a number 0-100."""

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[{"role": "user", "content": prompt}],
                max_tokens=10,
                temperature=0.3
            )
            
            score_text = response.choices[0].message.content.strip()
            # Extract number
            import re
            match = re.search(r'\d+', score_text)
            if match:
                score = int(match.group())
                return min(100, max(0, score))
            return 50
        except:
            return 50
    
    def _take_break(self, student: str):
        """Take a fun break"""
        print(f"\n🎮 BREAK TIME for {student}!")
        break_result = self.break_manager.take_break(student, "normal")
        print(f"   Activity: {break_result.get('activity', {}).get('name', 'Quick break')}")
        print(f"   {break_result.get('message', 'Take a moment to relax...')}")
        print(f"   (Refreshing before continuing...)\n")
    
    def _save_session_log(self, student: str, questions: int, avg_score: float, 
                          pass_rate: float, passed: int):
        """Save session log"""
        log = {
            "timestamp": datetime.now().isoformat(),
            "student": student,
            "questions": questions,
            "avg_score": avg_score,
            "pass_rate": pass_rate,
            "passed": passed,
            "discoveries": len(self.discoveries_this_session),
            "discovery_ids": [d["discovery"].id for d in self.discoveries_this_session]
        }
        
        log_file = self.log_dir / "session_logs.jsonl"
        with open(log_file, "a") as f:
            f.write(json.dumps(log) + "\n")
    
    def get_pending_reviews(self):
        """Get all items pending Manus review"""
        return {
            "conversations": self.recorder.get_pending_reviews(),
            "discoveries": self.discovery_detector.get_pending_reviews()
        }
    
    def manus_review_discovery(self, discovery_id: str, is_new: bool, 
                                sources: list, notes: str, action: str):
        """Manus reviews a discovery"""
        return self.discovery_detector.manus_review(
            discovery_id=discovery_id,
            is_new=is_new,
            verification_sources=sources,
            verification_notes=notes,
            action=action
        )


def main():
    """Run the rigorous learning system"""
    system = RigorousLearningSystem()
    
    # Run sessions for both students
    students = ["Stratify", "Principia"]
    
    for student in students:
        result = system.run_learning_session(student, num_questions=10)
        print(f"\n{student} completed: {result}")
        
    # Show pending reviews
    pending = system.get_pending_reviews()
    print(f"\n{'='*60}")
    print("PENDING MANUS REVIEWS")
    print(f"{'='*60}")
    print(f"Conversations to review: {len(pending['conversations'])}")
    print(f"Discoveries to review: {len(pending['discoveries'])}")
    
    # Show discovery statistics
    disc_stats = system.discovery_detector.get_statistics()
    print(f"\nDiscovery Statistics:")
    print(f"  Total detected: {disc_stats['total_discoveries']}")
    print(f"  Pending review: {disc_stats['pending_review']}")
    print(f"  By type: {disc_stats['by_type']}")
    
    # Show recording statistics
    rec_stats = system.recorder.get_statistics()
    print(f"\nRecording Statistics:")
    print(f"  Total records: {rec_stats['total_records']}")
    print(f"  Flagged for review: {rec_stats['flagged_for_review']}")
    print(f"  New math detected: {rec_stats['new_math_detected']}")


if __name__ == "__main__":
    main()
